[platformio]
default_envs = teensy41
src_dir = src
include_dir = include
test_dir = test

[env:teensy41]
platform = teensy@4.18.0
board = teensy41
framework = arduino
monitor_speed = 115200
monitor_filters = time
build_flags =
    -Wall
    -Wextra
    -Wpedantic
lib_deps =
    br3ttb/PID@^1.2.1
